config/routes.rb
Rails.application.routes.draw do
  resources :currency_converters

  root 'currency_converters#index'

  post 'currency_converters/calculate_conversion' => 'currency_converters#calculate_conversion'

end

app/models/currency_converter.rb
class CurrencyConverter < ActiveRecord::Base
  has_many :exchange_rates
end

app/models/exchange_rate.rb
# @author Alain Mauri
# this class calculates the exchange rate
# related bewteen two currencies
# default currency rate is assumed to be 1
# in database all other rates are saved
# all methods are static ones
# no need to instantiate the class

require 'nokogiri'
require 'open-uri'

class ExchangeRate < ActiveRecord::Base
  belongs_to :currency_converter

  # defining a scope to take only last 90 days rates 
  # older rates are not deleted
  ExchangeRate.scope :filter_by_date, -> (date) {where(" DATE(ecb_time) <= ? and DATE(ecb_time)>=?", date, date - 90.days)}

  # ecb url as a constant

  ECB_URL = "http://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml"

  # this is the method that does the actual conversion
  # it finds the selected currencies and their rates and then performs
  # the conversion rate following the formula rate_to/rate_from
  # @param rate_date date that to which rates are referred
  # @param from_id id of the currency that needs to be converted
  # @param to_id   id of the goal currency
  # @return conversion ratio (big decimal) or nil
  def self.at(rate_date, from_id, to_id)
    # using begin rescue so that we could return nil if something occurs
    begin
      # find the needed currencies
      cur_from = CurrencyConverter.find(from_id)
      cur_to = CurrencyConverter.find(to_id)

      # if currencies both exist find the related rates
      # and do the conversion
      if cur_from and cur_to
        if cur_from.default_currency
          rate_from = self.get_default_rate
        else
          rate_from = cur_from.exchange_rates.find_by_ecb_time(rate_date).rate
        end
        if cur_to.default_currency
          rate_to = self.get_default_rate
        else
          rate_to = cur_to.exchange_rates.find_by_ecb_time(rate_date).rate
        end
        # if both rates exist we can do the real calculation
        if rate_from and rate_to
          return rate_to/rate_from
        end
      end
      # to rescue from an error we could write in a log, a message
      # give some feedback or other
    rescue => e
      # logging the error message and the stacktrace
      logger.error e.message
      logger.error e.backtrace.join("\n")
      return nil
    end
    # in any other case return nil
    return nil
  end

  # returns the default rate which is 1 by definition
  def self.get_default_rate
    return 1
  end

  # method that parses ECB data only
  # ecb rates url is set as a constant
  # the method uses xpath to find all the nodes that have the time attribute
  # following ecb rates xml structure
  # it then parses all children to save data
  def self.read_ecb_data
    ecb_xml = Nokogiri::XML(open(ECB_URL))
    # selecting all nodes with time attribute
    ecb_xml.xpath("//*[@time]").each do |node|
      cur_time = node['time']
      # parsing each children and save data
      node.children.each do |rate|
        cur_slug = rate['currency']
        cur_rate = rate['rate']
        self.save_data(cur_time, cur_slug, cur_rate)
      end
    end
  end

  # this method saves data in database
  # if a currency is already in database
  # and the rate is not there it saves only the rate
  # otherwise it saves currency and rate
  # @param cur_time date of the rate
  # @param cur_slug current currency
  # @param cur_rate ecb rate of the currency
  def self.save_data(cur_time, cur_slug, cur_rate)
    begin
      # finding out if a currency is already in database
      currency = CurrencyConverter.find_by_currency_slug(cur_slug)

      # if it doesn't exist create a new one and save it
      if !currency
        currency = CurrencyConverter.new(currency_slug: cur_slug)
        currency.save
      end

      # find if a rate for the currency selected slug is there
      # if note create a new one
      # if it exists let's assume that it is not changed
      rate = currency.exchange_rates.find_by_ecb_time(Date.parse(cur_time))
      if !rate
        rate = ExchangeRate.new(ecb_time: cur_time, rate: cur_rate.to_f, currency_converter_id: currency.id)
        rate.save
      end
    rescue => e
      # logging the error message and the stacktrace
      logger.error e.message
      logger.error e.backtrace.join("\n")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/currency_converters_controller.rb
class CurrencyConvertersController < ApplicationController
  before_action :set_currency_converter, only: [:show, :edit, :update, :destroy]

  # GET /currency_converters
  # GET /currency_converters.json
  def index
    @currency_converters = CurrencyConverter.all
    @rates_dates = ExchangeRate.all.filter_by_date(Date.today)
  end


  # This one calls ExchangeRate.at and calculate the conversion
  def calculate_conversion
    converted_amount = nil

    # checking parameters before calculating the conversion rate
    if currency_converter_params[:rate_date] != "" or currency_converter_params[:from_cur] != "" or currency_converter_params[:to_cur] != ""
      rate = ExchangeRate.at( currency_converter_params[:rate_date].to_date, currency_converter_params[:from_cur], currency_converter_params[:to_cur])
      converted = false
      # rate is not nil go on and do the conversion
      if rate
        converted_amount = currency_converter_params[:amount].to_f * rate
        # rounding the amount to 5 decimal places
        converted_amount = converted_amount.round(5)
        converted = true

        # write the success message
        message = I18n.t('success_message', amount: converted_amount.to_s).html_safe
      else
        # failure message
        message = I18n.t('failure').html_safe
      end
    else
      # missing data message
      converted = false
      message = I18n.t('missed_data').html_safe
    end
    respond_to do |format|
      if converted
        format.json {render json: {success: true, message: message, amount: converted_amount} }
      else
        format.json {render json: {success: false, message: message, amount: ""}, status: 422 }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_converter_params
      params.permit(:rate_date, :amount, :from_cur, :to_cur)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_converters_helper.rb
module CurrencyConvertersHelper
end

app/views/currency_converters/_exchange_calculator.html.erb
<div class="row">
  <div class="col-xs-12 col-ms-12 col-md-11 col-lg-11">
    <%= form_tag currency_converters_calculate_conversion_path, id: 'conversion_rate', method: 'post', class: "form-horizontal", remote: true  do %>
      <div class="form-group">
          <%= label_tag :rate_view, I18n.t('label_date'), class: "col-xs-12 col-ms-12 col-md-1 col-lg-1" %>
          <div class="col-xs-12 col-ms-12 col-md-11 col-lg-11">
            <%= text_field_tag :rate_view %>
            <%= hidden_field_tag :rate_date %>
          </div>
      </div>
      <div class="form-group">
          <%= label_tag :amount, I18n.t('label_amount'), class: "col-xs-12 col-ms-12 col-md-1 col-lg-1"  %>
          <div class="col-xs-12 col-ms-12 col-md-2 col-lg-2">
            <%= text_field_tag :amount, '' , size: 4 %>
          </div>
          <%= label_tag :from_cur, I18n.t('label_from'), class: "col-xs-12 col-ms-12 col-md-1 col-lg-1" %>
          <div class="col-xs-12 col-ms-12 col-md-8 col-lg-8">
            <%= select_tag :from_cur, options_from_collection_for_select(@currency_converters, :id, :currency_slug), prompt: I18n.t('from_ccy') %>
          </div>
      </div>
      <div class="form-group">
          <div class="col-xs-12 col-ms-12 col-md-3 col-lg-3">&nbsp;</div>
          <%= label_tag :to_cur, I18n.t('label_to'),class: "col-xs-12 col-ms-12 col-md-1 col-lg-1" %>
          <div class="col-xs-12 col-ms-12 col-md-8 col-lg-8">
            <%= select_tag :to_cur, options_from_collection_for_select(@currency_converters, :id, :currency_slug), prompt: I18n.t('to_ccy') %>
          </div>
      </div>
      <div class="form-group">
        <div class="col-xs-12 col-ms-12 col-md-12 col-lg-12">
          <%= submit_tag I18n.t('label_submit'), class: "btn btn-default" %>
        </div>
      </div>
    <% end %>
  </div>
</div> <!-- end row -->
<div class="modal" id="modal_result">
  <div class="modal-dialog" role="document">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
          <div id="result"></div>
      </div> <!-- end body -->
  </div> <!-- end content -->
</div><!-- end document -->
</div>
</div>
<script>
  $('#rate_view').datepicker({
    dateFormat: "dd/mm/yy",
    altFormat: "yy-mm-dd",
    altField: "#rate_date"
  });
  /*
  * this workaround it to correct a behaviour of jquery ui datepicker
  * if a date is selected from the "history" of the widget the alt field
  * was not updated
  */
  $('#rate_view').on("change", function(){
    var widget = $.data(this, "datepicker");
    $.datepicker._setDateFromField(widget);
    $.datepicker._updateAlternate(widget);
  });
</script>

app/views/currency_converters/index.html.erb
<div class="row">
  <div class="col-xs-11 col-ms-11 col-md-1 col-lg-1">
  </div>
  <div class="col-xs-10 col-ms-10 col-md-10 col-lg-10">
    <div class="bd-pageheader">
      <h1><%= I18n.t('title') %></h1>
    </div>
    <%= render "exchange_calculator" %>
  </div>
  <div class="col-xs-11 col-ms-11 col-md-1 col-lg-1">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FreeagentTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row" id='main_container'>
    <%= yield %>
  </div>
</div>

</body>
</html>